[package]
name = "particle_filter"
version = "0.2.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.10.0"
rand_distr = "0.6.0"
enum-iterator = "2"
num-traits = "0.2"
trait-set = "0.3"
itertools = "0.14.0"
anyhow = "1.0.101"
hash_histogram = "0.14.0"
bit_grid = {git = "https://github.com/gjf2a/bit_grid"}
